%% 实验
function [] = do_exp(N,evaluation,problem,algorithmsandoperators,runs)
    %进行实验
    for i=1:length(algorithmsandoperators)/2
        run(N,evaluation,problem,algorithmsandoperators{2*i-1},algorithmsandoperators{2*i},runs);%设置种群规模，迭代次数，重复次数
    end
end

%% 分析MOEA算法在原油短期调度问题上的性能
function run(N,evaluation,problem,algorithm,operators,run_no)
	%调用算法(run_no记录运行的序号)
	main('-algorithm', str2func(algorithm),...
                    '-problem', str2func(problem), ...
                    '-N', N,...
                    '-run', run_no,...
                    '-operator', str2func(operators),...
                    '-evaluation',evaluation, ...
                    '-mode',3,...
                    '-outputFcn',@RecordResult);
end
